### ISSUE TITLE
v1.14.4 b2 Crash when shooting diamond bow

### ISSUE THREAD

**Issue by jaywcarman** [MrMarnic/ExtraBows#40]
Minecraft Version: 1.14.4
ModLoader version: Forge forge-1.14.4-28.2.0-installer
Mod Version: v1.14.4 b2
Short Description: Game Crash when shooting diamond bow
Crash log:
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 2/15/20 10:03 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.projectile.AbstractArrowEntity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
	at me.marnic.extrabows.common.events.ExtraBowsEventHandler$2.run(ExtraBowsEventHandler.java:137) ~[?:v1.14.4 b2] {re:classloading}
	at me.marnic.extrabows.api.util.TimeCommand$EndableTimeCommand.handle(TimeCommand.java:64) ~[?:v1.14.4 b2] {re:classloading}
	at me.marnic.extrabows.api.util.TimerUtil.handleTickEvent(TimerUtil.java:37) ~[?:v1.14.4 b2] {re:classloading}
	at me.marnic.extrabows.common.events.ExtraBowsEventHandler.worldTickEvent(ExtraBowsEventHandler.java:59) ~[?:v1.14.4 b2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_6_ExtraBowsEventHandler_worldTickEvent_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreServerTick(BasicEventHooks.java:114) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:762) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Linux (amd64) version 4.15.0-76-generic
	Java Version: 1.8.0_242, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 873148592 bytes (832 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.0
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.0-client.jar Minecraft {minecraft@1.14.4 DONE}
		luckyblock-1.14.4-7.9.1.jar Lucky Block {lucky@7.9.1 DONE}
		extrabows-v1.14.4+b2.jar Extra Bows {extrabows@v1.14.4 b2 DONE}
		car-1.14.4-2.0.18.jar Ultimate Car Mod {car@1.14.4-2.0.18 DONE}
		forge-1.14.4-28.2.0-universal.jar Forge {forge@28.2.0 DONE}
		shetiphiancore-1.14-3.6.0.jar ShetiPhian-Core {shetiphiancore@3.6.0 DONE}
		platforms-1.14-1.5.1.jar Platforms {platforms@1.5.0 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['five_and_six'/282, l='MOO!', x=-99.31, y=79.00, z=189.66]]
	Data Packs: vanilla, mod:car, mod:extrabows, mod:forge, mod:lucky, mod:platforms, mod:shetiphiancore
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
```

**Comment by MrMarnic** [comment]
You are using a very old version of the mod. Please update
